### ISSUE TITLE
Problems with connecting

### ISSUE THREAD

**Issue by Thelin90** [Landoop/fast-data-dev-connect-cluster#1]
Hello.

This may seem as a very stupid problem/question.

I have a locally setup kafka cluster on my computer. I want to use the fast-data-connect-cluster to connect to my locally setup of kafka.

The problem is that I never get the docker image to connect to my cluster, and I don't even seem to get the GUI to start up.

I was doing the following:

docker run -d --net=host -e ID=01 -e BS=localhost:9092 -e ZK=localhost:2181 -e SR=http://localhost/schema-registry:8081 -e HOST=docker landoop/fast-data-dev-connect-cluster

Where localhost is my IP-adress and docker is the ip-adress for the docker container.

I noticed that my container has no ports set, so I try to set it with -p 3030:3030 and -p 8000:8000 but it still seems like it has no ports.

Thank you

Simon

**Comment by Thelin90** [comment]
Just to add as a note, when I run the compose file it starts, should I edit the compose file to make it understand how it should be connected?
`version: '2'
services:
  localhost:
    # This will serve as our Kafka stack
    image: landoop/fast-data-dev:latest
    environment:
      - FORWARDLOGS=0
      - RUNTESTS=0
    ports:
      - 3030:3030
  connect-node-1:
    image: landoop/fast-data-dev-connect-cluster:latest
    depends_on:
      - localhost
    environment:
      - ID=01
      - BS=localhost:9092
      - ZK=localhost:2181
      - SR=http://localhost:8081
    connect-ui:
    image: landoop/kafka-connect-ui
    depends_on:
      - connect-node-1
    environment:
      - CONNECT_URL=http://connect-node-1:8083
    ports:
      - 8000:8000`

Where localhost is my local IP-adress.

But it complains:

ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.connect-node-1: 'connect-ui'
ezthesi@elxac3244m2:~/code/fast-data-connect-cluster$

**Comment by Thelin90** [comment]
The reason was that the SR version was not compatible with the Kafka version #facePalm

**Comment by andmarios** [comment]
Hi @Thelin90, thanks for following back!
