### ISSUE TITLE
SSL/TLS Connection to Broker

### ISSUE THREAD

**Issue by justinsoong** [Landoop/fast-data-dev-connect-cluster#2]
I'm guessing that for this feature to work need to be able to mount location of keystore, any plans to support this?

**Comment by andmarios** [comment]
Hello, thank you for your interest. As you found out only the PLAINTEXT protocol is supported for now.

Our plans for the future is to deprecate this docker image in favor of the images we provide for deployment via helm charts in kubernetes (<https://hub.docker.com/r/datamountaineer/>) —of course the new images won't work only with helm and k8s. There we support all configuration options. Unfortunately I can't provide a timeline for this transition.

**Comment by justinsoong** [comment]
Cool thanks, i'm building my own image now thanks for the inspiration!
